#! /usr/bin/python3.4

__author__ = 'nicolas'

from sys import stdin
from re import compile
from pylab import plot, show


def parse():
    va = []
    ls = []
    for line in stdin:
        print(line[:-1])
        p = compile("^(abscisse : )([+-]?\d+(\.\d+)?)( cm\trayon : )([+-]?\d+(\.\d+)?)( cm)")
        if p.match(line[:-1]):
            ret = p.findall(line[:-1])
            va.append(ret[0][1])
            ls.append(ret[0][4])
    return va, ls

if __name__ == "__main__":
    vac, lst = parse()
    if len(vac) == 0 or len(lst) == 0:
        exit(84)
    x = vac
    y = lst
    plot(x, y)
    show()
